import React from 'react';
import * as Icon from 'react-feather';

const navigationConfig = [
  {
    id: 'dashboard-iuli',
    title: 'dashboard',
    type: 'item',
    icon: <Icon.Home size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin',
    permissioniuli: 'companies.dashboards.index',
  },
  {
    id: 'sales-dashboard',
    title: 'dashboard.sales.menu',
    type: 'item',
    icon: <Icon.Activity size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/sales-dashboard',
    permissioniuli: 'companies.dashboards.index',
  },
  {
    id: 'financial-dashboard',
    title: 'dashboard.financial.menu',
    type: 'item',
    icon: <Icon.BarChart2 size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/financial-dashboard',
    permissioniuli: 'companies.dashboards.index',
  },

  {
    id: 'dre',
    title: 'statement.dre',
    type: 'item',
    icon: <Icon.PieChart size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/dre',
    permissioniuli: 'api.statements.getDre',
  },
  {
    id: 'dfc',
    title: 'statement.dfc',
    type: 'item',
    icon: <Icon.PieChart size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/dfc',
    permissioniuli: 'api.statements.getDfc',
  },
  {
    id: 'detailed-statement',
    title: 'statement.detailed-statement',
    type: 'item',
    icon: <Icon.PieChart size={20} />,
    navLink: '/admin/statements/detailed',
    permissioniuli: 'api.statements.getDfc',
  },
  {
    id: 'supplier-list',
    title: 'suppliers.list',
    type: 'item',
    icon: <Icon.ShoppingCart size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/supplier/list',
    children: ['/admin/supplier/edit/:company_id?'],
    permissioniuli: 'companies.suppliers.index',
  },
  {
    id: 'client-list',
    title: 'clients.list',
    type: 'item',
    icon: <Icon.User size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/client/list',
    children: ['/admin/client/edit/:company_id?'],
    permissioniuli: 'companies.clients.index',
  },
  {
    id: 'receivable-list',
    title: 'receivables.list',
    type: 'item',
    icon: <Icon.ArrowUpRight size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/receivable/list',
    children: ['/admin/receivable/edit/:transaction_id?'],
    permissioniuli: 'companies.receivables.index',
  },
  {
    id: 'payable-list',
    title: 'payables.list',
    type: 'item',
    icon: <Icon.ArrowDownRight size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/payable/list',
    children: ['/admin/payable/edit/:transaction_id?'],
    permissioniuli: 'companies.payables.index',
  },
  {
    id: 'bank-account-list',
    title: 'bank-account.list',
    type: 'item',
    icon: <Icon.Briefcase size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/bank-account/list',
    children: ['/admin/bank-account/edit/:bank_account_id?'],
    permissioniuli: 'companies.bank-accounts.index',
  },
  {
    id: 'transfers.list',
    title: 'transfers.list',
    type: 'item',
    icon: <Icon.Repeat size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/transfer/list',
    children: ['/admin/transfer/edit/:transfer_id?'],
    permissioniuli: 'transfers.index',
  },
  {
    id: 'project-list',
    title: 'projects.list',
    type: 'item',
    icon: <Icon.Layers size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/project/list',
    children: ['/admin/project/edit/:project_id?'],
    permissioniuli: 'companies.projects.index',
  },
  {
    id: 'cost-center-list',
    title: 'cost_centers.list',
    type: 'item',
    icon: <Icon.Layout size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/cost-center/list',
    children: ['/admin/cost-center/edit/:cost_center_id?'],
    permissioniuli: 'companies.cost-centers.index',
  },
  // {
  //   id: 'budget-list',
  //   title: 'budgets.list',
  //   type: 'item',
  //   icon: <Icon.DollarSign size={20} />,
  //   permissions: ['admin', 'editor'],
  //   navLink: '/admin/budget/list',
  //   children: ['/admin/budget/edit/:budget_id?'],
  //   permissioniuli: 'companies.budgets.index',
  // },
  {
    id: 'product-link-list',
    title: 'product_links.list',
    type: 'item',
    icon: <Icon.Link size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/product-link/list',
    children: ['/admin/product-link/edit/:product_link_id?'],
    permissioniuli: 'api.companies.product-links.list-by-company',
  },
  {
    id: 'product-list',
    title: 'products.list',
    type: 'item',
    icon: <Icon.Box size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/product/list',
    children: ['/admin/product/edit/:product_id?'],
    permissioniuli: 'companies.products.index',
  },
  {
    id: 'sales-list',
    title: 'sales.list',
    type: 'item',
    icon: <Icon.CreditCard size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/sale/list',
    children: ['/admin/sale/edit/:sale_id?', '/admin/sale/import'],
    permissioniuli: 'companies.sales.index',
  },
  {
    id: 'invoices-download',
    title: 'invoices',
    type: 'item',
    icon: <Icon.File size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/invoice/download',
    children: ['/admin/invoice/download'],
    permissioniuli: 'invoice-downloads.index',
  },
  {
    id: 'purchases-list',
    title: 'purchases.list',
    type: 'item',
    icon: <Icon.ShoppingBag size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/purchase/list',
    children: ['/admin/purchase/edit/:purchase_id?'],
    permissioniuli: 'companies.purchases.index',
  },
  {
    id: 'period-closure-list',
    title: 'period_closure.list',
    type: 'item',
    icon: <Icon.Lock size={20} />,
    permissions: ['admin', 'editor'],
    navLink: '/admin/period-closure/list',
    permissioniuli: 'bank-accounts.period-closures.index',
  },
  {
    id: 'stock',
    title: 'Estoque',
    type: 'item',
    icon: <Icon.Package size={20} />,
    permissions: ['admin'],
    navLink: '/stock',
    permissioniuli: 'stock.index',
  },
  {
    id: 'dashboard',
    title: 'Settings',
    type: 'collapse',
    icon: <Icon.Tool size={20} />,
    children: [
      {
        id: 'iuli_plans',
        title: 'iuli_plans',
        type: 'item',
        icon: <Icon.Flag size={12} />,
        navLink: '/admin/iuli-plan/list',
        permissioniuli: 'isIuliAdmin',
      },
      {
        id: 'iuli_payments',
        title: 'iuli_payments',
        type: 'item',
        icon: <Icon.DollarSign size={12} />,
        navLink: '/admin/iuli-payment/list',
        permissioniuli: 'isIuliAdmin',
      },
    ],
    permissioniuli: 'isIuliAdmin',
  },
];

export default navigationConfig;
